# Generated by Django 6.0.1 on 2026-09-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_question_correct_option_question_option_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('qna', 'Question & Answer'), ('mcq', '4 Option MCQ')], default='qna', max_length=3),
        ),
    ]
