# Generated by Django 6.0.1 on 2026-09-09 03:21

from django.db import migrations


def backfill_question_type(apps, schema_editor):
    """
    Auto-tag existing questions:
    - If option_b is non-empty, it's an MCQ question
    - Otherwise, it's a Q&A question
    """
    Question = apps.get_model('user', 'Question')
    for q in Question.objects.all():
        if q.option_b and q.option_b.strip():
            q.question_type = 'mcq'
        else:
            q.question_type = 'qna'
        q.save(update_fields=['question_type'])


def reverse_backfill(apps, schema_editor):
    """Reverse: set all back to default 'qna'."""
    Question = apps.get_model('user', 'Question')
    Question.objects.all().update(question_type='qna')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_add_question_type'),
    ]

    operations = [
        migrations.RunPython(backfill_question_type, reverse_backfill),
    ]
