# Generated by Django 6.1 on 2026-10-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='user.student')),
            ],
            options={
                'verbose_name': 'Student OTP',
                'verbose_name_plural': 'Student OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
