# Generated by Django 6.1 on 2026-08-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_student_email_remove_student_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='ReportCard',
        ),
        migrations.DeleteModel(
            name='StudentAttempt',
        ),
    ]
